### PR TITLE
Styles/launch screen ios

### PR DESCRIPTION
**Pull request by CFDevelopment**
- ios launch screen added with new styles
- dynamic progress bar must be added

### CODE REVIEW

**Comment by CFDevelopment** [comment]
It seems to be a dependency to some react native library.. I can try and
refactor it out and see if all is well

**Comment by GregTheGreek** [comment]
@CFDevelopment Dive into it, see what you come up with. otherwise ill merge

**Comment by CFDevelopment** [comment]
ok

**Comment by CFDevelopment** [comment]
It looked like it was only referenced once and i removed it, removed all
node modules, rebuilt and installed and it wont run and build on xcode

**Pull request closed without merging**
