### PR TITLE
Minkee deletecontact

### PR DESCRIPTION
**Pull request by minkeesung**
@CFDevelopment @GregTheGreek @masterrom

### CODE REVIEW

**Comment by GregTheGreek** [comment]
@minkeesung Please fix.

**Comment by GregTheGreek** [comment]
@minkeesung conflcits

**Comment by minkeesung** [comment]
resolved merge conflicts @GregTheGreek @masterrom

**Comment by priom** [comment]
What's going on with this PR? @GregTheGreek @CFDevelopment @masterrom @minkeesung

**Comment by GregTheGreek** [comment]
@masterrom whats going on

**Pull request merged**
